apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-hostpath-
spec:
  entrypoint: test-hostpath
  volumes:
    - name: workdir
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
  templates:
  - name: test-hostpath
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo This is the output:
        echo ls -l /mnt/vol: `ls -l /mnt/vol`
        echo pwd: `pwd`
        echo ls /mnt: `ls /mnt`
        touch /mnt/vol/test.txt
        echo ls -l /mnt/vol: `ls -l /mnt/vol`
        echo ls /: `ls /`
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol

